#!/usr/bin/env bash
# Set up Pi on a fresh machine, end to end:
#   1. symlink the config into ~/.pi/agent (backing up any real files in the way)
#   2. create models.json by prompting for provider credentials (not committed to git)
#   3. use the existing Node, or bootstrap an LTS Node via nvm if none is found
#   4. ensure GNU Make >= 4.4 (building it if the system make is too old; needed
#      to compile the tree-sitter native modules)
#   5. wipe stale node_modules and install each extension's npm dependencies
#   6. verify the native modules load under pi's Node (no ABI mismatch)
#   7. install the pi CLI globally, install pi-web in ~/.pi/agent/pi-web with
#      its embedded pi aligned to the CLI, and write pinned launchers
# Idempotent — safe to re-run.
#
# Symlinks (into this dotfiles repo, so edits stay version-controlled):
#   ~/.pi/agent/agents          -> agentic/pi/agents
#   ~/.pi/agent/extensions      -> agentic/pi/extensions
#   ~/.pi/agent/prompts         -> agentic/pi/prompts
#   ~/.pi/agent/settings.json   -> agentic/pi/settings.json
#   ~/.pi/agent/keybindings.json-> agentic/pi/keybindings.json
#   ~/.pi/agent/SYSTEM.md       -> agentic/pi/SYSTEM.md
#   ~/.pi/agent/AGENTS.md       -> agentic/pi/AGENTS.md
#   ~/.pi/agent/mcp.json        -> agentic/pi/mcp.json
#   ~/.pi/agent/skills/<name>   -> agentic/skills/<name>   (one link per skill; see skills/sync.sh)
#   ~/.pi/agent/themes          -> agentic/pi/themes
#   ~/.pi/agent/pi-web/         managed pi-web install; generated by setup.sh
#
# Dependencies: each extension declares its own npm deps in a per-extension
# package.json, but node_modules/ is gitignored — so a fresh copy has the code
# but none of the installed packages. This installs them in every extension
# dir that has a package.json.
#
# Some extensions (read, search, _outliner) use native modules (better-sqlite3,
# tree-sitter). Node.js 25+ requires C++20 for native builds, so CXXFLAGS is set
# accordingly. build-essential + python3 are installed as a compile fallback on apt.
#
# Usage: ./setup.sh [--ci] [--no-bin] [--bin-only]
#   --ci         use `npm ci` (clean, lockfile-exact) instead of `npm install`
#   --no-bin     skip step 7 (leave pi/pi-web installs and launchers alone)
#   --bin-only   sync the symlinks/config (idempotent) and run step 7, skipping the
#                build toolchain and the extension npm installs (steps 4-6) — use it
#                to fix pi/pi-web versions or the launchers without a full reinstall
#
# Version pins for step 7 (all optional):
#   PI_VERSION=1.2.3      install this exact pi CLI version (`latest` = newest)
#   PI_WEB_VERSION=0.8.11 install this exact pi-web version
# With no pins, step 7 keeps the installed pi CLI version and makes pi-web embed
# exactly that pi build (see step 7). Neither package is auto-upgraded — use
# PI_VERSION=latest to pull the newest pi.
#
# If a real file/dir is in the way of a symlink (e.g. configs copied in
# manually), it's backed up to <name>.bak and replaced with the symlink.

set -eu

# Resolve this script's dir (= agentic/pi), following symlinks. POSIX-safe:
# uses $0, so this works whether invoked as `./setup.sh`, `bash setup.sh`,
# or `sh setup.sh`.
SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"
REPO_AGENTIC="$(cd "$SCRIPT_DIR/.." && pwd)"   # agentic/
EXT_DIR="$SCRIPT_DIR/extensions"
PI_HOME="$HOME/.pi/agent"

INSTALL_CMD="install"
SKIP_BIN=0
BIN_ONLY=0
for arg in "$@"; do
  case "$arg" in
    --ci) INSTALL_CMD="ci" ;;
    --no-bin) SKIP_BIN=1 ;;
    --bin-only) BIN_ONLY=1 ;;
    *) echo "unknown option: $arg" >&2; exit 2 ;;
  esac
done

# --- 1. Symlinks ------------------------------------------------------------

# "link_name -> target" pairs, relative to PI_HOME / the repo respectively.
link() {
  local name="$1" target="$2"
  local dest="$PI_HOME/$name"

  if [ ! -e "$target" ]; then
    echo "!!! $name: target missing ($target), skipping" >&2
    return
  fi

  # Already the correct symlink? Leave it.
  if [ -L "$dest" ] && [ "$(readlink "$dest")" = "$target" ]; then
    echo "=== $name: already linked"
    return
  fi

  # A real directory here is intentional curation (e.g. a `skills` dir that
  # aggregates skills from several repos) — clobbering it into a repo-only
  # symlink would silently drop those. Leave it untouched; remove it yourself
  # if you want setup.sh to manage this link.
  if [ -d "$dest" ] && [ ! -L "$dest" ]; then
    echo "=== $name: real directory present — left as-is (not symlinked)"
    return
  fi

  # A real file (not a symlink) lives here — e.g. a config copied in manually.
  # Back it up to <name>.bak and replace it with the symlink.
  if [ -e "$dest" ] && [ ! -L "$dest" ]; then
    backup="$dest.bak"
    i=1
    while [ -e "$backup" ]; do backup="$dest.bak.$i"; i=$((i + 1)); done
    mv "$dest" "$backup"
    echo "    backed up existing $name -> $backup"
  fi

  ln -sfn "$target" "$dest"
  echo "--- $name -> $target"
}

echo "Linking Pi config into $PI_HOME"
mkdir -p "$PI_HOME"
link agents           "$SCRIPT_DIR/agents"
link extensions       "$SCRIPT_DIR/extensions"
link prompts          "$SCRIPT_DIR/prompts"
link settings.json    "$SCRIPT_DIR/settings.json"
link keybindings.json "$SCRIPT_DIR/keybindings.json"
link SYSTEM.md        "$SCRIPT_DIR/SYSTEM.md"
link AGENTS.md        "$SCRIPT_DIR/AGENTS.md"
link mcp.json         "$SCRIPT_DIR/mcp.json"
link themes           "$SCRIPT_DIR/themes"

# Skills get one symlink per skill instead of one for the whole folder, because
# ~/.pi/agent/skills also aggregates skills owned by other repos
# (~/.agents/skills, gitsky/internal-agentic-coding). sync.sh only ever touches
# links that point into this repo, so those survive a re-run.
"$REPO_AGENTIC/skills/sync.sh" --dest "$PI_HOME/skills" \
  || echo "!!! skills: unresolved entries, see the CHECK lines above" >&2
echo
echo

# --- 2. models.json ---------------------------------------------------------
# Create models.json by prompting the user for provider credentials.
# This file contains secrets and is NOT committed to git.

echo "=== Setting up models.json ==="

# Skip if already exists (user may have custom config)
if [ -f "$PI_HOME/models.json" ]; then
  echo "models.json already exists at $PI_HOME/models.json — skipping"
else
  echo "models.json not found — creating new configuration"
  echo
  echo "Configure your LLM provider. Press Enter to keep the default value."
  echo

  read -rp "Base URL [http://127.0.0.1:8080/v1]: " base_url
  read -rp "API key [default]: " api_key
  read -rp "Model ID: " model_id
  read -rp "Context window [262144]: " context_window

  base_url="${base_url:-http://127.0.0.1:8080/v1}"
  api_key="${api_key:-default}"
  model_id="${model_id:-}"
  context_window="${context_window:-262144}"

  if [ -z "$model_id" ]; then
    echo "Error: Model ID is required"
    exit 1
  fi

  echo
  echo "Writing models.json..."

  # Build JSON file
  json_file="$PI_HOME/models.json"

  printf '{\n  "providers": {\n    "default": {\n' > "$json_file"
  printf '      "baseUrl": "%s",\n' "$base_url" >> "$json_file"
  printf '      "api": "openai-completions",\n' >> "$json_file"
  printf '      "apiKey": "%s",\n' "$api_key" >> "$json_file"
  printf '      "models": [{\n' >> "$json_file"
  printf '        "id": "%s",\n' "$model_id" >> "$json_file"
  printf '        "contextWindow": %s\n' "$context_window" >> "$json_file"
  printf '      }]\n' >> "$json_file"
  printf '    }\n' >> "$json_file"
  printf '  }\n' >> "$json_file"
  printf '}\n' >> "$json_file"

  echo "--- models.json created at $PI_HOME/models.json"
  echo
fi

echo

# --- 2b. MCP secrets --------------------------------------------------------
# mcp.json is committed, so per-server secrets are kept out of git and read at
# launch via `!cat` command markers. Provision the referenced secret files here.
# This dir is outside the repo (never committed).

echo "=== Setting up MCP secrets ==="
SECRETS_DIR="$PI_HOME/secrets"
mkdir -p "$SECRETS_DIR"
chmod 700 "$SECRETS_DIR"

tavily_secret="$SECRETS_DIR/tavily-api-key"
if [ -s "$tavily_secret" ]; then
  echo "tavily-api-key already present — skipping"
else
  read -rp "Tavily API key (blank to skip; tavily search stays unconfigured): " tavily_key
  if [ -n "$tavily_key" ]; then
    printf '%s' "$tavily_key" > "$tavily_secret"
    chmod 600 "$tavily_secret"
    echo "--- wrote $tavily_secret"
  else
    echo "skipped — tavily will fail to start until $tavily_secret exists"
  fi
fi

echo

# --- 3. Node -----------------------------------------------------------------

# IMPORTANT: the native modules (better-sqlite3, tree-sitter) are node-gyp
# addons whose compiled binaries are ABI-LOCKED to a Node major
# (NODE_MODULE_VERSION) — they are NOT portable across versions. They must be
# built with the SAME Node that executes `pi`, or pi crashes at startup with
# "compiled against a different Node.js version".
#
# `pi`'s launcher is `#!/usr/bin/env node`, so pi runs under the first `node` on
# PATH at launch — on macOS that's Homebrew node@24, while an interactive shell
# often defaults to nvm's Node (lazy, not on PATH until sourced). Building with
# the wrong one is exactly what breaks pi. So we still only bootstrap an LTS Node
# via nvm when none exists at all, but then resolve the exact node pi will use
# (see resolve_pi_node below) and build with THAT — a shell that happens to have
# a different node active can no longer poison the build.
NVM_DIR="${NVM_DIR:-$HOME/.nvm}"
export NVM_DIR

if ! command -v node >/dev/null 2>&1; then
  echo "Node not found — installing LTS via nvm"
  if ! command -v curl >/dev/null 2>&1; then
    echo "error: curl needed to install nvm/Node — install curl, then re-run" >&2
    exit 1
  fi
  # nvm.sh and the nvm functions aren't written for `set -eu`, so relax it
  # while we drive nvm, then restore.
  set +eu
  if [ ! -s "$NVM_DIR/nvm.sh" ]; then
    echo "Installing nvm into $NVM_DIR…"
    curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
  fi
  # shellcheck source=/dev/null
  . "$NVM_DIR/nvm.sh"
  nvm install --lts
  nvm use --lts
  nvm alias default 'lts/*'
  set -eu

  if ! command -v node >/dev/null 2>&1; then
    echo "error: nvm failed to provide Node — see output above" >&2
    exit 1
  fi
fi
echo "Using Node $(node -v)"
echo

if ! command -v npm >/dev/null 2>&1; then
  echo "error: npm still not on PATH after Node setup" >&2
  exit 1
fi

# Resolve the Node that will actually execute `pi`, and build native modules with
# it (see the note above). Priority: explicit $PI_NODE override > an absolute node
# hard-coded in pi's shebang > a non-nvm node matching `env node` when nvm isn't
# loaded (Homebrew/system) > whatever node exists (Linux/Spark: nvm's node is the
# real one pi uses too).
PI_BIN="$(command -v pi 2>/dev/null || true)"
resolve_pi_node() {
  if [ -n "${PI_NODE:-}" ] && command -v "$PI_NODE" >/dev/null 2>&1; then
    command -v "$PI_NODE"; return
  fi
  if [ -n "$PI_BIN" ]; then
    sb="$(head -1 "$PI_BIN" 2>/dev/null)"
    case "$sb" in
      "#!/"*/node) echo "${sb#\#!}"; return ;;   # absolute node in shebang
    esac
  fi
  for c in /opt/homebrew/bin/node /usr/local/bin/node /usr/bin/node; do
    [ -x "$c" ] && { echo "$c"; return; }
  done
  command -v node 2>/dev/null
}
PI_NODE="$(resolve_pi_node)"
if [ -z "$PI_NODE" ] || [ ! -x "$PI_NODE" ]; then
  echo "error: could not locate the Node that runs pi (set PI_NODE=/path/to/node)" >&2
  exit 1
fi
PI_NODE_BIN_DIR="$(cd "$(dirname "$PI_NODE")" && pwd)"
echo "Building native modules with pi's Node: $PI_NODE ($("$PI_NODE" -v), ABI $("$PI_NODE" -e 'process.stdout.write(process.versions.modules)'))"
echo

# --- 7. pi / pi-web binaries and pinned launchers ---------------------------
#
# Defined here (right after Node resolution, which it needs) and run last, after
# the native-module check. Two rules drive it, both learned the hard way:
#
#  a) ONE Node runs everything. The extensions' native addons (tree-sitter
#     grammars, better-sqlite3) are node-gyp binaries ABI-locked to a Node major,
#     so pi, pi-web and their npm installs must all run under $PI_NODE. The bins
#     npm installs say `#!/usr/bin/env node`, i.e. they follow whatever the
#     calling shell has active — and with nvm lazy-loaded that can change mid
#     session, which is how pi-web ended up on Node 25 against modules built for
#     Node 24: every native load failed and the `read` extension died. The
#     wrappers written below pin $PI_NODE, so PATH can no longer sabotage this.
#
#  b) ONE pi version, everywhere. pi-web runs pi *in-process* and depends on an
#     exact pi-coding-agent version, so `npm i -g @agegr/pi-web` silently ships an
#     older pi than the CLI you type in a terminal — two different pi builds over
#     the same session files, with no env var or option to redirect it. So pi-web
#     is installed from a generated manifest in $PI_HOME/pi-web whose npm
#     `overrides` pin forces the embedded pi SDK to the exact CLI version, and
#     both surfaces run one build. (Verified: pi-web 0.8.11 boots and creates
#     agent-session services against pi 0.84.4 this way.)

# Marker line identifying a launcher this script generated.
LAUNCHER_MARKER="# pi-setup: launcher (generated by agentic/pi/setup.sh)"

# Managed pi-web install (generated manifest + node_modules).
PIWEB_HOME="$PI_HOME/pi-web"

# Version of an installed package ("" when absent).
pkg_version() {
  [ -f "$1/package.json" ] || return 0
  "$PI_NODE" -e 'try{process.stdout.write(String(require(process.argv[1]).version||""))}catch(e){}' "$1/package.json"
}

# Absolute path to a package's bin entry ("" when unresolvable).
pkg_bin() {
  [ -f "$1/package.json" ] || return 0
  "$PI_NODE" -e 'const fs=require("fs"),p=require("path");try{const f=p.resolve(p.dirname(process.argv[1]),(require(process.argv[1]).bin||{})[process.argv[2]]);if(fs.existsSync(f))process.stdout.write(f)}catch(e){}' "$1/package.json" "$2"
}

# npm_install_global <pkg> [version]
npm_install_global() {
  spec="$1"; ver="${2:-}"
  [ -n "$ver" ] && spec="$1@$ver"
  echo "--- npm install -g $spec (Node $("$PI_NODE" -v))"
  if ! (cd "$PI_HOME" 2>/dev/null || cd /tmp; PATH="$PI_NODE_BIN_DIR:$PATH" npm install -g --no-audit --no-fund --loglevel=warn "$spec"); then
    echo "!!! npm install -g $spec failed" >&2
    return 1
  fi
}

# write_launcher <name> <js entry>: generate $PI_HOME/bin/<name> pinning $PI_NODE.
write_launcher() {
  name="$1"; entry="${2:-}"
  if [ -z "$entry" ]; then
    echo "!!! $name: npm bin entry not found — leaving any existing launcher alone" >&2
    return 1
  fi
  mkdir -p "$PI_HOME/bin"
  dest="$PI_HOME/bin/$name"
  # Never silently overwrite something this script didn't generate.
  if [ -e "$dest" ] && [ ! -L "$dest" ] && ! grep -q "$LAUNCHER_MARKER" "$dest" 2>/dev/null; then
    mv "$dest" "$dest.bak"
    echo "    backed up existing $dest -> $dest.bak"
  fi
  {
    echo '#!/bin/sh'
    echo "$LAUNCHER_MARKER"
    echo "# Pins $PI_NODE so a shell with another Node active (nvm) cannot load the"
    echo "# extensions' native addons under the wrong ABI. Regenerate with setup.sh."
    echo "exec \"$PI_NODE\" \"$entry\" \"\$@\""
  } > "$dest.tmp"
  chmod +x "$dest.tmp"
  mv "$dest.tmp" "$dest"
  echo "--- $dest -> $PI_NODE $entry"
}

setup_binaries() {
  echo "=== pi / pi-web binaries and launchers"

  npm_root="$(PATH="$PI_NODE_BIN_DIR:$PATH" npm -g root 2>/dev/null || true)"
  if [ -z "$npm_root" ] || [ ! -d "$npm_root" ]; then
    echo "!!! npm's global root not found — skipping; install pi and pi-web manually" >&2
    echo "    under $PI_NODE, then re-run setup.sh"
    return 1
  fi
  pi_dir="$npm_root/@earendil-works/pi-coding-agent"
  piweb_dir="$PIWEB_HOME/node_modules/@agegr/pi-web"

  # --- the pi CLI -----------------------------------------------------------
  # Never auto-upgraded: re-running setup.sh must not change which pi you run.
  have_pi="$(pkg_version "$pi_dir")"
  if [ "${PI_VERSION:-}" = "latest" ]; then
    echo "--- PI_VERSION=latest — installing the newest pi"
    npm_install_global "@earendil-works/pi-coding-agent" "latest" || return 1
    have_pi="$(pkg_version "$pi_dir")"
  elif [ -z "$have_pi" ]; then
    echo "--- pi not installed under $PI_NODE — installing"
    npm_install_global "@earendil-works/pi-coding-agent" "${PI_VERSION:-latest}" || return 1
    have_pi="$(pkg_version "$pi_dir")"
  elif [ -n "${PI_VERSION:-}" ] && [ "$PI_VERSION" != "$have_pi" ]; then
    echo "--- pi $have_pi != PI_VERSION=$PI_VERSION — installing the pinned version"
    npm_install_global "@earendil-works/pi-coding-agent" "$PI_VERSION" || return 1
    have_pi="$(pkg_version "$pi_dir")"
  else
    echo "--- pi $have_pi installed (PI_VERSION=latest ./setup.sh --bin-only to upgrade)"
  fi
  if [ -z "$have_pi" ]; then
    echo "!!! no pi CLI under $PI_NODE — cannot align pi-web" >&2
    return 1
  fi

  # --- pi-web, installed from a generated manifest --------------------------
  # A global `npm i -g @agegr/pi-web` bundles its own (older) pi SDK, so remove
  # one if present: it would shadow the aligned install and re-open the skew.
  if [ -d "$npm_root/@agegr/pi-web" ]; then
    echo "--- removing global pi-web $(pkg_version "$npm_root/@agegr/pi-web") — pi-web now lives in"
    echo "    $PIWEB_HOME, where its embedded pi can be pinned to the CLI's version"
    if ! (cd "$PI_HOME" && PATH="$PI_NODE_BIN_DIR:$PATH" npm rm -g --no-audit --no-fund --loglevel=warn @agegr/pi-web); then
      echo "!!! could not remove the global @agegr/pi-web — remove it by hand" >&2
    fi
  fi

  installed_piweb="$(pkg_version "$piweb_dir")"
  want_piweb="${PI_WEB_VERSION:-}"
  if [ -z "$want_piweb" ]; then
    want_piweb="$(PATH="$PI_NODE_BIN_DIR:$PATH" npm view @agegr/pi-web version 2>/dev/null || true)"
    # Offline (or registry hiccup): keep the pi-web already installed here.
    [ -n "$want_piweb" ] || want_piweb="$installed_piweb"
  fi
  if [ -z "$want_piweb" ]; then
    echo "!!! no pi-web version to install (no registry access and none installed)" >&2
    return 1
  fi

  mkdir -p "$PIWEB_HOME"
  manifest="$PIWEB_HOME/package.json"
  "$PI_NODE" -e '
    const fs = require("fs");
    const pi = "@earendil-works/pi-coding-agent";
    fs.writeFileSync(process.argv[1], JSON.stringify({
      name: "pi-web-managed",
      private: true,
      description: "Managed by agentic/pi/setup.sh: pi-web with its embedded pi SDK forced to match the pi CLI. Edit via setup.sh, not by hand.",
      dependencies: { "@agegr/pi-web": process.argv[2], [pi]: process.argv[3] },
      overrides: { [pi]: "$" + pi },
    }, null, 2) + "\n");
  ' "$manifest.tmp" "$want_piweb" "$have_pi" || return 1
  if [ -f "$manifest" ] && cmp -s "$manifest.tmp" "$manifest"; then
    rm -f "$manifest.tmp"
    echo "=== pi-web manifest unchanged"
  else
    mv "$manifest.tmp" "$manifest"
    echo "--- installing pi-web $want_piweb with its embedded pi pinned to $have_pi"
    if ! (cd "$PIWEB_HOME" && PATH="$PI_NODE_BIN_DIR:$PATH" npm install --legacy-peer-deps --no-audit --no-fund --loglevel=warn); then
      echo "!!! pi-web install failed ($PIWEB_HOME)" >&2
      return 1
    fi
  fi

  have_piweb="$(pkg_version "$piweb_dir")"
  embedded="$(pkg_version "$PIWEB_HOME/node_modules/@earendil-works/pi-coding-agent")"
  if [ "$embedded" != "$have_pi" ]; then
    echo "!!! pi-web's embedded pi is ${embedded:-nothing}, the CLI is $have_pi — the override" >&2
    echo "    did not take effect. Inspect $manifest (the overrides entry must name $pi_dir)." >&2
    return 1
  fi
  echo "--- pi-web $have_piweb runs pi $embedded — the same build as the CLI"

  write_launcher "pi" "$(pkg_bin "$pi_dir" pi)"
  write_launcher "pi-web" "$(pkg_bin "$piweb_dir" pi-web)"

  # Front the PATH with the pinned launchers. npm's own bins use `#!/usr/bin/env
  # node` and live in a directory nvm can jump in front of, so relying on PATH
  # ordering alone re-opens the ABI hole; ~/.local/bin is on PATH nearly
  # everywhere and precedes /opt/homebrew/bin (and nvm's bin dir) on macOS.
  local_bin="$HOME/.local/bin"
  if mkdir -p "$local_bin" 2>/dev/null; then
    for name in pi pi-web; do
      [ -x "$PI_HOME/bin/$name" ] || continue
      dest="$local_bin/$name"
      if [ -L "$dest" ] && [ "$(readlink "$dest")" = "$PI_HOME/bin/$name" ]; then
        echo "=== $dest already linked"
        continue
      fi
      if [ -e "$dest" ] && [ ! -L "$dest" ]; then
        mv "$dest" "$dest.bak"
        echo "    backed up existing $dest -> $dest.bak"
      fi
      ln -s "$PI_HOME/bin/$name" "$dest"
      echo "--- $dest -> $PI_HOME/bin/$name"
    done
  fi

  # Smoke test: the launcher must actually run pi under $PI_NODE.
  if out="$("$PI_HOME/bin/pi" --version 2>&1 | head -1)"; then
    echo "--- launcher check: pi $out"
  else
    echo "!!! $PI_HOME/bin/pi failed to run: $out" >&2
    return 1
  fi
  if ! "$PI_HOME/bin/pi-web" --help >/dev/null 2>&1; then
    echo "!!! $PI_HOME/bin/pi-web failed to run (--help)" >&2
    return 1
  fi

  # Tell the user if something earlier on PATH still shadows the pinned launcher.
  found_pi="$(command -v pi 2>/dev/null || true)"
  case "$found_pi" in
    "$PI_HOME/bin/pi"|"$local_bin/pi"|"") : ;;
    *) echo "!!! note: in this shell 'pi' resolves to $found_pi — start pi from"
       echo "    ~/.local/bin/pi (or put ~/.pi/agent/bin ahead on PATH) to use the pinned one." >&2 ;;
  esac

  echo "Summary: node $PI_NODE (ABI $("$PI_NODE" -e 'process.stdout.write(process.versions.modules)')),"
  echo "         pi CLI $have_pi, pi-web $have_piweb running that same pi build"
}

if [ "$BIN_ONLY" = 1 ]; then
  setup_binaries
  exit $?
fi

# --- 4. Build toolchain & GNU Make ------------------------------------------

# Native modules (better-sqlite3, tree-sitter) compile on install and need a
# C/C++ toolchain + python3. On apt-based systems, install them if missing.
need_toolchain=false
command -v cc  >/dev/null 2>&1 || need_toolchain=true
command -v make >/dev/null 2>&1 || need_toolchain=true
command -v python3 >/dev/null 2>&1 || need_toolchain=true

if [ "$need_toolchain" = true ]; then
  if command -v apt-get >/dev/null 2>&1; then
    echo "Build toolchain missing — installing build-essential python3"
    sudo apt-get update && sudo apt-get install -y build-essential python3
    echo
  else
    echo "!!! build toolchain (cc/make/python3) missing and apt-get not found." >&2
    echo "    Install a C/C++ compiler + python3 manually if native modules fail." >&2
    echo
  fi
fi

# node-gyp needs GNU Make >= 4.4 to build the tree-sitter modules. Make 4.3
# (Ubuntu 24.04's default) has a target-matching regression that breaks on the
# node-addon-api ".stamp" path node-gyp emits (Release/obj.target/../...stamp),
# so the compile dies with "No rule to make target". When the system make is
# too old, build 4.4.1 once and point node-gyp at it via $MAKE.
make_lt_44() {
  v="$(make --version 2>/dev/null | head -1 | awk '{print $NF}')"   # e.g. 4.3 / 4.4.1
  mj="${v%%.*}"; r="${v#*.}"; mn="${r%%.*}"
  [ -z "$mj" ] && return 0
  [ "$mj" -gt 4 ] 2>/dev/null && return 1
  [ "$mj" -eq 4 ] 2>/dev/null && [ "${mn:-0}" -ge 4 ] 2>/dev/null && return 1
  return 0
}

if make_lt_44; then
  MAKE_PREFIX="$HOME/.cache/pi-setup/make-4.4.1"
  if [ ! -x "$MAKE_PREFIX/bin/make" ]; then
    echo "System make is < 4.4 ($(make --version 2>/dev/null | head -1)) — building GNU Make 4.4.1"
    if ! command -v curl >/dev/null 2>&1; then
      echo "error: curl needed to fetch GNU Make sources" >&2
      exit 1
    fi
    build_tmp="$(mktemp -d)"
    (
      cd "$build_tmp" &&
      curl -fsSLO https://ftpmirror.gnu.org/make/make-4.4.1.tar.gz &&
      tar xf make-4.4.1.tar.gz &&
      cd make-4.4.1 &&
      ./configure --prefix="$MAKE_PREFIX" >/dev/null &&
      make -j"$(nproc 2>/dev/null || echo 2)" >/dev/null &&
      make install >/dev/null
    ) || { echo "error: failed to build GNU Make 4.4.1" >&2; rm -rf "$build_tmp"; exit 1; }
    rm -rf "$build_tmp"
  fi
  MAKE="$MAKE_PREFIX/bin/make"
  export MAKE   # node-gyp honours $MAKE
  echo "Using $("$MAKE" --version | head -1) for native builds ($MAKE)"
  echo
fi

# --- 5. Extension dependencies ----------------------------------------------

echo "Installing extension dependencies in $EXT_DIR"
echo

failed=""
installed=0

for pkg in "$EXT_DIR"/*/package.json; do
  [ -e "$pkg" ] || continue
  dir="$(dirname "$pkg")"
  name="$(basename "$dir")"

  # Skip extensions with no declared dependencies.
  if ! grep -q '"dependencies"\|"devDependencies"' "$pkg"; then
    echo "--- $name: no deps, skipping"
    continue
  fi

  # Wipe any node_modules first for a clean, reproducible install (clears any
  # half-built or wrong-arch native modules left by a previous failed run).
  rm -rf "$dir/node_modules"

  echo "--- $name: npm $INSTALL_CMD (Node $("$PI_NODE" -v))"
  # Force pi's Node to the front of PATH so npm/node-gyp build against its ABI,
  # regardless of which node is otherwise active in this shell.
  if (cd "$dir" && PATH="$PI_NODE_BIN_DIR:$PATH" CXXFLAGS="--std=c++20" npm "$INSTALL_CMD" --legacy-peer-deps); then
    installed=$((installed + 1))
  else
    echo "!!! $name: install failed" >&2
    failed="$failed $name"
  fi
  echo
done

echo "Done: $installed extension(s) installed."
echo

# --- 5a. Swift helper binaries that extensions spawn -------------------------
# vm-isolation runs every bash call through vm-runner, and its safety check
# fails CLOSED: with no .build/debug/vm-runner the tool blocks *every* command
# ("BLOCKED: Safety check unavailable — command blocked (spawn … vm-runner …
# ENOENT)"), pi included. npm never builds that binary and .build/ is gitignored,
# so a machine that only ran setup.sh ends up with a pi that cannot run a single
# shell command. Build it wherever a Swift toolchain exists; warn elsewhere
# instead of failing, since the extension is only load-bearing on macOS.
for pkg in "$EXT_DIR"/*/vm-runner/Package.swift; do
  [ -e "$pkg" ] || continue
  dir="$(dirname "$pkg")"
  name="$(basename "$(dirname "$dir")")"
  if [ -x "$dir/.build/debug/vm-runner" ]; then
    echo "=== $name: vm-runner already built"
    continue
  fi
  if ! command -v swift >/dev/null 2>&1; then
    echo "!!! $name: swift not found — vm-runner NOT built. If this extension gates" >&2
    echo "    the bash tool, no command will run until you build it by hand:" >&2
    echo "    (cd $dir && swift build)" >&2
    continue
  fi
  echo "--- $name: swift build (vm-runner)"
  # Debug, not release: that is the path the extension spawns.
  if ! (cd "$dir" && swift build); then
    echo "!!! $name: swift build failed — the bash tool may refuse every command." >&2
  fi
done
echo

# --- 5b. One copy of pi's own types for the whole extension tree -------------
#
# Extensions import @earendil-works/* and typebox. Those must resolve to the
# build pi actually runs on — not to the published copies that each extension's
# own `dependencies: {"@earendil-works/pi-coding-agent": "*"}` pulls in, and not
# to whatever global install happens to be on PATH. Mixed copies make the same
# interface two unrelated types (TS2719 on every registerTool), which is why
# tsconfig.json maps those specifiers onto $EXT_DIR/node_modules and this step
# fills that directory in.
#
# Runs AFTER the npm installs above because npm prunes entries it did not
# create, which would otherwise delete these links.

echo "Linking pi's own packages into $EXT_DIR/node_modules"

pi_pkg=""
for launcher in "${PI_HOME:-$HOME/.pi/agent}/bin/pi" "$(command -v pi 2>/dev/null)"; do
  [ -f "$launcher" ] || continue
  cli="$(grep -o '/[^" ]*pi-coding-agent/dist/[^"]*\.js' "$launcher" 2>/dev/null | head -1)"
  [ -n "$cli" ] || continue
  cand="${cli%/dist/*}"
  [ -f "$cand/package.json" ] && { pi_pkg="$cand"; break; }
done
if [ -z "$pi_pkg" ]; then
  # Fall back to the global root of the Node that runs pi.
  npm_root="$("$PI_NODE" -e 'process.stdout.write(require("node:child_process").execSync("npm root -g").toString().trim())' 2>/dev/null)"
  cand="$npm_root/@earendil-works/pi-coding-agent"
  [ -f "$cand/package.json" ] && pi_pkg="$cand"
fi
if [ -z "$pi_pkg" ]; then
  echo "!!! could not locate pi's package directory — typechecking will fail with" >&2
  echo "    TS2307 on @earendil-works/* (set PI_NODE, or install pi globally)." >&2
else
  echo "--- pi package: $pi_pkg"
  # Root devDependencies (@types/node) — the per-extension loop only visits
  # */package.json, so the extensions root is installed here.
  if [ -f "$EXT_DIR/package.json" ] && [ ! -d "$EXT_DIR/node_modules/@types/node" ]; then
    echo "--- installing typecheck devDependencies in $EXT_DIR"
    (cd "$EXT_DIR" && PATH="$PI_NODE_BIN_DIR:$PATH" npm install --no-audit --no-fund) \
      || echo "!!! npm install failed in $EXT_DIR" >&2
  fi
  mkdir -p "$EXT_DIR/node_modules/@earendil-works"
  ln -sfn "$pi_pkg" "$EXT_DIR/node_modules/@earendil-works/pi-coding-agent"
  for m in "$pi_pkg"/node_modules/@earendil-works/*; do
    [ -d "$m" ] || continue
    ln -sfn "$m" "$EXT_DIR/node_modules/@earendil-works/$(basename "$m")"
  done
  [ -d "$pi_pkg/node_modules/typebox" ] \
    && ln -sfn "$pi_pkg/node_modules/typebox" "$EXT_DIR/node_modules/typebox"
  echo "--- linked $(ls "$EXT_DIR/node_modules/@earendil-works" | tr '\n' ' ')plus typebox"
fi
echo
if [ -n "$failed" ]; then
  echo "Failed:$failed" >&2
  echo "Native modules failed to build. Check you're on LTS Node ($(node -v)), that" >&2
  echo "build-essential + python3 are installed, and GNU Make >= 4.4, then re-run." >&2
  exit 1
fi

# --- 6. Verify native modules load under pi's Node --------------------------
# An ABI mismatch otherwise stays silent until pi crashes at startup. Load every
# freshly built binding under pi's Node and fail loudly here if any was compiled
# against a different Node major.
echo
echo "Verifying native modules load under pi's Node ($("$PI_NODE" -v))…"
abi_bad=""
for nodefile in $(find "$EXT_DIR"/*/node_modules -name '*.node' -path '*/build/Release/*' 2>/dev/null); do
  err="$("$PI_NODE" -e 'try{require(process.argv[1])}catch(e){process.stderr.write(e.message)}' "$nodefile" 2>&1 >/dev/null)"
  case "$err" in
    *NODE_MODULE_VERSION*|*"different Node.js version"*)
      echo "!!! ABI mismatch: $nodefile" >&2
      abi_bad="yes" ;;
  esac
done
if [ -n "$abi_bad" ]; then
  echo "error: native modules were built against the wrong Node ABI — they must" >&2
  echo "       match pi's Node ($PI_NODE). Re-run with a correct PATH or set PI_NODE." >&2
  exit 1
fi
echo "All native modules load cleanly under pi's Node."

# --- 7 (run). pi / pi-web binaries and pinned launchers ---------------------
# See the function definition after step 3 for why this exists.
if [ "$SKIP_BIN" = 1 ]; then
  echo
  echo "Skipping pi/pi-web install and launcher setup (--no-bin)."
else
  echo
  setup_binaries
fi

echo
echo "Setup complete. Start pi with:  pi      (or the web UI with:  pi-web)"
